task_client:
  consumer:
    queue_url: "https://sqs.ap-south-1.amazonaws.com/827635254891/shashwat-dts"
    region: "ap-south-1"
    max_messages: 5
    wait_time_seconds: 10
    visibility_timeout: 30
    workers: 25
  producer:
kube_client:
  namespace: "default"